services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ligeirinho'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'data:/var/lib/postgresql/data'
      
volumes:
  data: